/*
update ds set ds.EDOCUMENTTYPE = 0
from AxDB.dbo.AXXDOCSALESSTRUCTURESEGMENTSETUP ds
where ds.DOCPOSID = '00017'
*/
select ds.EDOCUMENTTYPE, *
from AxDB.dbo.AXXDOCSALESSTRUCTURESEGMENTSETUP ds
where ds.DOCPOSID = '00017'

/*
update rt set rt.AXXCOMEINVOICEDOCPOSID = '00017'
from AxDB.dbo.RETAILTERMINALTABLE rt
*/

select rt.AXXCOMEINVOICEDOCPOSID, rt.TERMINALID, rt.*
from AxDB.dbo.RETAILTERMINALTABLE rt
where rt.TERMINALID = 'jona'
